persistence:
    uri: jdbc:postgresql://localhost/bits
    username: bits
    password: bits

gameplay-mechanics:
    monitor:
        block-break: true
        block-place: true
        
        entity-leash: true
        entity-kill: true
        entity-shear: true

        item-brew: true
        item-enchant: true
        item-furnace: true
        
        painting-create: true

        player-regenerate: true
        player-shoot: true
        player-chat: true
        player-death: true
        player-sleep: true
        player-author: true
        player-egg: true
        player-fish: true
        player-eat: true
        player-join: true
        player-move: true

        portal-create: true
        
        vehicle-move: true

        world-change: true
